@baseUrl = http://localhost:3003/api
@username = juanceto01
@password = asd123

### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "{{username}}",
    "name": "Juan",
    "password": "{{password}}"
}


### login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


### create blog
# @name createBlog
@token = {{login.response.body.token}}

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "My first blog",
    "author": "{{username}}",
    "url": "fullstackopen.com",
    "likes": 0
}


### delete created blog
@blogId = {{createBlog.response.body.id}}
@token = {{login.response.body.token}}


### add like

PUT {{baseUrl}}/blogs/698e603d9e9c1ba579d323fa/like
Content-Type: application/json
Authorization: Bearer {{token}}


###
DELETE {{baseUrl}}/blogs/{{blogId}}
Authorization: Bearer {{token}}