@baseUrl = http://localhost:3003/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW4xMjMiLCJpZCI6IjY5N2JkMjA1Mzc3ZTM2M2QxNDRhMGZmNSIsImlhdCI6MTc2OTcyMjY1MX0.62O6o6gLPO33_9VnKVpouKw_2uxpHtAkA3Sx6Joukwg

### 1. GET 
GET {{baseUrl}}/blogs


### POST
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "juan's blog",
    "author": "juan",
    "url": "https://fullstackopen.com/",
    "likes": 5
}


### PUT
PUT {{baseUrl}}/blogs/
Content-Type: application/json

{
    "title": "juan's blog",
    "author": "Midudev Fan",
    "url": "https://fullstackopen.com/",
    "likes": 100
}

### DELETE
DELETE {{baseUrl}}/blogs/6973fada55e7f3a4f4ad04c6
//Authorization: Bearer {{token}}